[package]
name = "hctarcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler = { path = "compiler", version = "0.1.0" }
runtime = { path = "runtime", version = "0.1.0" }
