[workspace]
members = [
    "compiler",
    "runtime",
]
exclude = [
    "vendor/scratch-compiler",  # For tests
    "target/scratch_out"  # Generated
]
resolver = "2"

[profile.release]
lto = true
strip = "debuginfo"
panic = "abort"
opt-level = "s"
