[workspace]
members = [
    "gen/linrays",
    "gen/tres",
    "gen/sanity",
    "gen/mandelbrot",
    "gen/teststamp",
]
resolver = "2"

[profile.release]
panic = "abort"
strip = "debuginfo" # true
# `lto = true
